### ISSUE TITLE
Labeling discrepancy

### ISSUE THREAD

**Issue by bng919** [aryntoombs/aryntoombs.github.io#1]
I noticed a slight discrepancy between the Non-ICU and ICU patients by vaccine dose charts. It looks like the colors for 'within 14 days' and 'after 14 days' are swapped for both first and second doses between the two sets of charts.

The labels in `non_icu_count_chart.png` and `non_icu_perc_chart.png` are: 
![image](https://user-images.githubusercontent.com/65152888/126857966-83f62221-6c1e-4cba-9a96-0b823a0e72b6.png)

Where as the labels in `icu_count_chart.png` and `icu_perc_chart.png` are:
![image](https://user-images.githubusercontent.com/65152888/126857982-541cc124-8928-42db-a194-c9992b34cfc0.png)

Was this discrepancy intentional? I personally would find it easier to read if they were consistent :)

**Comment by aryntoombs** [comment]
Hi Ben,

These two charts are currently set up to factor for themselves based on magnitude of the data, and that order defines the colors. You make a good point however, and I will change this so the colors are consistent between the two charts for the vaccination for easier comparison for the Monday update.

**Comment by bng919** [comment]
Thanks Aryn! Keep up the great work!
